### ISSUE TITLE
Help us articulate The Carpentries Values

### ISSUE THREAD

**Issue by serahrono** [carpentries/conversations#21] opened 2019-08-01 15:30 UTC
Shared values and goals have long been the starting point of communities of practice as they identify changes they want to see and start working together towards these changes. The Carpentries started out with a clear goal - **teaching foundational computational skills to researchers worldwide**. Something that is also important and unique about our community is how we work and engage with each other. As a community, values are important to us and we consider that we have a set of shared values. However, we have not yet articulated what these values are. 

[The Carpentries Executive Council](https://carpentries.org/governance) did some preliminary work on this at their in-person meeting in 2018, and [The Carpentries team](https://carpentries.org/team/) has also done some initial exercises in this regard. 

To be truly reflective of the community however, we believe that it is important for community involvement to be an integral part of creating these value statements. We would love to hear from you, our community, and we intend to use this information to inform and create a beta draft of a set of value statements for The Carpentries.

**Help us articulate The Carpentries Values by answering these three questions:**

1. Envision people you think of as representative of The Carpentries community. What words would you use to describe these people? (No need to identify them, briefly outline their characteristics.)

1. The workshops we run, calls we hold, interactions we have on various platforms, and guidelines we use to uphold these interactions are but a few things that make us who we are as a community. With this in mind, in 2-3 sentences, how would you describe The Carpentries community culture?

1. From your understanding of our community culture and the demeanour of individuals that constitute The Carpentries, what specific  actions would you like The Carpentries community to take up or uphold in everyday Carpentries conversations going forwards?

Please answer these two questions by
- leaving comments directly under this issue, or
- responding to [this discuss thread on TopicBox](https://carpentries.topicbox.com/groups/discuss/T9029fc4692993ab1/input-needed-help-us-articulate-the-carpentries-values), or
- filling out [this Google form](https://forms.gle/gZmafyLVKAHBqfgc6) anonymously

_Issue updated on September 12 2019 to include the question above_

**Comment by jduckles** [comment] 2019-08-06 23:36
My thoughts are encapsulated over here in my adaptation of The Social Dynamics of Debian to The Carpentries: https://github.com/carpentries/conversations/issues/17

**Comment by remram44** [comment] 2019-08-06 23:37
Seem related: previous discussions for [mission statement](https://github.com/carpentries/executive-council-info/issues/1) and [value statement](https://github.com/carpentries/executive-council-info/issues/2)

**Comment by hoytpr** [comment] 2019-08-07 14:29
1. The most impressive individuals encountered representing the Carpentries core values are those with extraordinary knowledge, and even power, who recognize the importance of contributing to the scientific community by embracing those with less knowledge, and/or less power, but who share a passionate ideology of inclusiveness, and truth. These individuals recognize that everyone can learn. As such these individuals use their positions to influence policy for expanded, improved mentorship, and expanded, improved inclusion both social and in interdisciplinary science. 

2. The Carpentries community culture is an important representation of new paradigms in the community of scientists that will uplift scientific reputation (through openness and reproducibility) scientific accountability, self-care, and proper perspective to the effort and accuracy involved in developing scientific knowledge. By recognizing the need for new approaches to interdisciplinary science, the Carpentries represent a community of ***support*** to improve community interactions that increase the rate of knowledge acquisition without the destructive or counterproductive aspects of publish or perish.  It's commitment to spread that culture makes it a rare and potentially disruptive platform to improve science for the greater good.

**Comment by malvikasharan** [comment] 2019-08-08 16:18
1) Words to describe people in this community: 

Inclusive, forward and global thinking, adaptive, growth-mindset, skill-building, transparent decision-making, low-barrier, value exchange

**Comment by naupaka** [comment] 2019-08-08 18:28
1. Enthusiastic, welcoming, inclusive.
2. A place for the intersection of tech knowledge/skills and pedagogy in the context of inclusive and welcoming attitudes towards all peoples and paths.

**Comment by chrispunjoku** [comment] 2019-08-09 18:54
Q. 1: My answer

Passionate

Composed

Caring

Respectful
Selfless

Q. 2: My idea:
This is a community with a culture of oneness in diversity, collaboration,
openness, and passion for sharing essential computing and data skills with
best practices and utmost respect for one another.  We learn as much as we
teach, because to us a learner is also a teacher.

My 2 kobo.

Chris Prince Udochukwu *Njọkụ*, Ph.D.
Computer Communications Centre
University of Nigeria, Nsukka 410001
@DrCPUNjoku

 We mustn't remain with old ways of doing things,

especially if they're not yielding optimum results.

**Comment by zjsteyn** [comment] 2019-08-26 15:25
Envision people you think of as representative of The Carpentries community. What words would you use to describe these people? (No need to identify them, briefly outline their characteristics.)

- Passionate about seeing growth and enabling others. Compassionate. Understanding, supportive

The workshops we run, calls we hold, interactions we have on various platforms, and guidelines we use to uphold these interactions are but a few things that make us who we are as a community. With this in mind, in 2-3 sentences, how would you describe The Carpentries community culture?

There is a sense of family, there can be challenges sometimes but my experience is that we try to grow as a family. That means addressing challenges and supporting each other where we can. But also as the extended family grows in the future thinking broader about support would be important.

**Comment by kariljordan** [comment] 2021-09-22 18:50
On November 18, 2019, we introduced [The Carpentries Core Values](https://carpentries.org/blog/2019/11/carpentries-values/) (see below). Thank you so much for this issue. I will close it now, but if there is more feedback that anyone has feel free to reopen.

The Nine Core Values of The Carpentries


_At The Carpentries we…_
**Act Openly**
We believe that transparency, honesty, and fairness are keys to fostering trust within an open community.

**Empower One Another**
We help people build knowledge by creating a conducive environment for the exchange of skills, perspectives and experiences that empower people and enable them to reach their potential.

**Value All Contributions**
We value all contributions by individuals and entities to our community, code, lessons and broader ecosystem as long as those contributions adhere to The Carpentries Code of Conduct.

_We are…_
**Always Learning**
We value a growth mindset in all that we do and strive for continuous improvement, evolving ourselves and our methodologies, being responsive, curious, receptive to feedback, and eager to learn.

**Inclusive of All**
We advocate for inclusivity - welcoming and extending empathy and kindness - to leverage contributions from all community members, regardless of their identity or expression.

_We champion…_
**People First**
We believe that the individuals who make up our community are the most important part of our organisation and our strongest resource. We strive to make decisions that lower barriers for individual participation.

**Access for All**
We value accessibility as core, and create multiple avenues for participation where all people can learn and contribute.

**Community Collaboration**
Our curricula and programs are developed by and with community members. We see collaboration across borders, domains and initiatives as a pathway to empower people and realise shared goals.

**Strength through Diversity**
Appreciating that identities are complex and individual, we believe in empowering a diverse group of people to work with data and code to answer the questions important to them and address challenges in science and society.

**Closed by kariljordan** 2021-09-22 18:50 UTC
